services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    working_dir: /workspace

    # Keep container running
    command: sleep infinity

    # Add capabilities needed for development
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Environment variables
    environment:
      - DEBIAN_FRONTEND=noninteractive
